
server.port=9091
spring.datasource.url=jdbc:mysql://localhost:3306/skill_swap_db
spring.datasource.username=root
spring.datasource.password=Naveen@1103
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Fix: Serialize LocalDateTime as ISO string, not as array [2026,9,24,10,57,28]
spring.jackson.serialization.write-dates-as-timestamps=false
